PersonelProject.ToDo.Web1/Areas/Admin/Controllers/UrgencyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PersonelProject.ToDo.Business.Interfaces;
using PersonelProject.ToDo.Entities.Concrete;
using PersonelProject.ToDo.Web1.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonelProject.ToDo.Web1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class UrgencyController : Controller
    {
        private readonly IUrgencyService _urgencyService;
        public UrgencyController(IUrgencyService urgencyService)
        {
            _urgencyService = urgencyService;
        }

        public IActionResult Index()
        {
            TempData["Active"] = "urgency";
            List<Urgency> urgencies = _urgencyService.GetirButunu();

            List<UrgencyListViewModel> model = new List<UrgencyListViewModel>();

            foreach (var item in urgencies)
            {
                UrgencyListViewModel urgencymodel = new UrgencyListViewModel();
                urgencymodel.Id = item.Id;
                urgencymodel.Definition = item.Definition;

                model.Add(urgencymodel);

            }
            return View(model);
        }

        public IActionResult AddUrgency()
        {
            TempData["Active"] = "urgency";
            return View(new UrgencyAddViewModel());
        }

        [HttpPost]
        public IActionResult AddUrgency(UrgencyAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                _urgencyService.Kaydet(new Urgency()
                {
                    Definition = model.Definition

                });

                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult UpdateUrgency(int id)
        {
            TempData["Active"] = "urgency";
            var urgency=_urgencyService.GetirIdCalisma(id);
            UrgencyUpdateViewModel model = new UrgencyUpdateViewModel
            {
                Id = urgency.Id,
                Definition = urgency.Definition

            };
            return View(model);
        }

        [HttpPost]
        public IActionResult UpdateUrgency(UrgencyUpdateViewModel model)
        {
            if (ModelState.IsValid)
            {
                _urgencyService.Guncelle(new Urgency
                {
                    Id = model.Id,
                    Definition = model.Definition

                });

                return RedirectToAction("Index");
            }
            return View(model);
        }



    }
}

PersonelProject.ToDo.Web1/Areas/Admin/Views/Urgency/AddUrgency.cshtml
@model UrgencyAddViewModel
@{
    ViewData["Title"] = "AddUrgency";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form class="w-75 mx-auto p-3" method="post">
    <div class="form-group">
        <label asp-for="@Model.Definition"></label>
        <span asp-validation-for="Definition" class="text-danger"></span>
        <input asp-for="Definition" type="text" class="form-control" />

    </div>
    <button type="submit" class="btn btn-info">Save</button>
</form>

@section JavaScript{


    <script src="~/lib/jqueryValidate/jquery.validate.min.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>
}

PersonelProject.ToDo.Web1/Areas/Admin/Views/Urgency/Index.cshtml
@model List<UrgencyListViewModel>


@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



@if (Model.Count != 0)
{<a asp-action="AddUrgency" asp-controller="Urgency" class="btn btn-warning my-2">Add Urgency</a>

    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th>
                    Definition
                </th>
                <th>
                    Process
                </th>


            </tr>

        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Definition</td>
                    <td>
                        <a asp-action="UpdateUrgency" asp-controller="Urgency" 
                           asp-route-id="@item.Id" class="btn btn-warning">Edit</a>
                    </td>
                </tr>
            }


        </tbody>

    </table>


}
else
{
    <div class="text-center lead mt-4 ">
        <p class="lead">
            You do not have any registration in the system.
        </p>
        <a asp-action="AddUrgency" asp-controller="Urgency" class="btn btn-warning my-2">Add Urgency</a>
    </div>
}

PersonelProject.ToDo.Web1/Areas/Admin/Views/Urgency/UpdateUrgency.cshtml
@model UrgencyUpdateViewModel
@{
    ViewData["Title"] = "UpdateUrgency";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form class="w-75 mx-auto p-3" method="post">
    <input asp-action="UpdateUrgency" type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="@Model.Definition"></label>
        <span asp-validation-for="Definition" class="text-danger"></span>
        <input asp-for="Definition" type="text" class="form-control" />

    </div>
    <button type="submit" class="btn btn-info">Save</button>
</form>

@section JavaScript{


    <script src="~/lib/jqueryValidate/jquery.validate.min.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>
}